//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPI_TestEntities : DbContext
    {
        public MPI_TestEntities()
            : base("name=MPI_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SQLSmartAuditData> SQLSmartAuditDatas { get; set; }
        public virtual DbSet<mas_patient> mas_patient { get; set; }
        public virtual DbSet<Sheet1_> Sheet1_ { get; set; }
        public virtual DbSet<tblExceptionsLog> tblExceptionsLogs { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblMasterPatientIndex> tblMasterPatientIndexes { get; set; }
        public virtual DbSet<tblPatientInfo> tblPatientInfoes { get; set; }
    }
}
