//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLSmartAuditData
    {
        public int AuditId { get; set; }
        public System.DateTime AuditDateTime { get; set; }
        public string AuditType { get; set; }
        public string AuditTable { get; set; }
        public string AuditUser { get; set; }
        public string AuditMachine { get; set; }
        public string AuditApp { get; set; }
        public string AuditData { get; set; }
    }
}
