//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExceptionsLog
    {
        public Nullable<int> NumberofRecords { get; set; }
        public Nullable<int> RecordsImported { get; set; }
        public Nullable<int> RecordsToAppend { get; set; }
        public Nullable<int> RecordsNotAppended { get; set; }
        public Nullable<int> RecordsToAppend2 { get; set; }
        public Nullable<int> RecordsNotAppended2 { get; set; }
        public Nullable<int> RecordsToDelete { get; set; }
        public Nullable<int> RecordsNotDeleted { get; set; }
        public Nullable<int> RecordsToDelete2 { get; set; }
        public Nullable<int> RecordsNotDeleted2 { get; set; }
        public Nullable<int> RecordsToUpdate { get; set; }
        public Nullable<int> RecordsNotUpdated { get; set; }
        public Nullable<int> RecordsToUpdate2 { get; set; }
        public Nullable<int> RecordsNotUpdated2 { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public string ExceptionsProcessed { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
