//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public string username { get; set; }
        public string mr { get; set; }
        public string account_number { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string patient_name { get; set; }
    }
}
