//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterPatientIndex
    {
        public string Flag { get; set; }
        public string Patient_Number { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Street { get; set; }
        public string Patient_City { get; set; }
        public string Patient_State { get; set; }
        public string Patient_Zip_Code { get; set; }
        public string Patient_Phone { get; set; }
        public string Social_Security_Number { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Sex_Code { get; set; }
        public string Marital_Status { get; set; }
        public string Race_Code { get; set; }
        public string Religion_Code { get; set; }
        public string Medicare_Number { get; set; }
        public string Medicaid_Number { get; set; }
        public string Blue_Cross_Number { get; set; }
        public string Medical_Record_Number { get; set; }
        public string Creation_Operator_ID { get; set; }
        public string Creation_Date { get; set; }
        public string Update_Date { get; set; }
        public string Update_Operator { get; set; }
    }
}
